In [1]:
import pandas as pd
import numpy as np
from faker import Faker # For generating fake data
from datetime import datetime, timedelta
import random # For random date generation

In [2]:
fake = Faker() # Initialize Faker to generate fake data
fake.name() # Example of generating a fake name using Faker

'Crystal Sloan'

In [3]:
NUM_USERS = 5000

In [4]:
users = []
events = []

# Generate user data

In [5]:
for user_id in range(1, NUM_USERS + 1):

    signup_date = fake.date_time_between(
        start_date='-90d',
        end_date='now'
    )

    variant = random.choice(['A', 'B']) # Randomly assign users to variant A or B

    users.append({
        'user_id': user_id,
        'signup_date': signup_date,
        'variant': variant
    })

# Generate event data

In [6]:
users_df = pd.DataFrame(users)
users_df.head()

   user_id         signup_date variant
0        1 2026-05-03 20:02:05       B
1        2 2026-05-07 13:25:22       B
2        3 2026-03-13 14:58:41       B
3        4 2026-05-06 06:13:15       B
4        5 2026-04-12 16:10:08       B

In [7]:
for _, row in users_df.iterrows(): # Iterate over each user to generate their event data

    user_id = row['user_id']
    signup_date = row['signup_date']
    variant = row['variant']

    # Every user signs up
    events.append({
        'user_id': user_id,
        'event': 'signup',
        'timestamp': signup_date,
        'variant': variant
    })

    # Activation probability
    activated = np.random.rand() < 0.65 # 65% chance of activation

    if activated:

        activation_time = signup_date + timedelta(
            hours=random.randint(1, 48)
        ) # Activation happens within 1 to 48 hours after signup

        events.append({
            'user_id': user_id,
            'event': 'activation',
            'timestamp': activation_time,
            'variant': variant
        })

        # Feature usage probability
        used_feature = np.random.rand() < 0.50 # 50% chance of using the feature after activation

        if used_feature: 

            feature_time = activation_time + timedelta(
                days=random.randint(1, 7)
            )

            events.append({
                'user_id': user_id,
                'event': 'feature_use',
                'timestamp': feature_time,
                'variant': variant
            })

            # Purchase probability
            purchased = np.random.rand() < 0.30 # 30% chance of making a purchase after using the feature

            if purchased:

                purchase_time = feature_time + timedelta(
                    days=random.randint(1, 10)
                )

                events.append({
                    'user_id': user_id,
                    'event': 'purchase',
                    'timestamp': purchase_time,
                    'variant': variant
                })

# Convert events to DataFrame

In [8]:
events_df = pd.DataFrame(events)
events_df.head(20)

    user_id        event           timestamp variant
0         1       signup 2026-05-03 20:02:05       B
1         1   activation 2026-05-04 01:02:05       B
2         2       signup 2026-05-07 13:25:22       B
3         2   activation 2026-05-08 21:25:22       B
4         3       signup 2026-03-13 14:58:41       B
5         4       signup 2026-05-06 06:13:15       B
6         4   activation 2026-05-07 21:13:15       B
7         4  feature_use 2026-05-10 21:13:15       B
8         5       signup 2026-04-12 16:10:08       B
9         5   activation 2026-04-13 14:10:08       B
10        5  feature_use 2026-04-15 14:10:08       B
11        6       signup 2026-05-14 16:11:57       A
12        6   activation 2026-05-16 08:11:57       A
13        6  feature_use 2026-05-17 08:11:57       A
14        6     purchase 2026-05-25 08:11:57       A
15        7       signup 2026-03-26 06:23:55       B
16        8       signup 2026-04-07 22:32:01       B
17        9       signup 2026-04-21 01:05:15       B
18        9   activation 2026-04-22 12:05:15       B
19        9  feature_use 2026-04-27 12:05:15       B

In [9]:
users_df.to_csv('../data/raw/users.csv', index=False)

events_df.to_csv('../data/raw/events.csv', index=False)

51700